// <auto-generated />
using System;
using DietDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietDB.Migrations
{
    [DbContext(typeof(DietContext))]
    [Migration("20230905202827_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DieticianMessage", b =>
                {
                    b.Property<int>("DieticiansId")
                        .HasColumnType("int");

                    b.Property<int>("MessagesId")
                        .HasColumnType("int");

                    b.HasKey("DieticiansId", "MessagesId");

                    b.HasIndex("MessagesId");

                    b.ToTable("DieticianMessage");
                });

            modelBuilder.Entity("DieticianOffice", b =>
                {
                    b.Property<int>("DieticianId")
                        .HasColumnType("int");

                    b.Property<int>("OfficesId")
                        .HasColumnType("int");

                    b.HasKey("DieticianId", "OfficesId");

                    b.HasIndex("OfficesId");

                    b.ToTable("DieticianOffice");
                });

            modelBuilder.Entity("DieticianVisit", b =>
                {
                    b.Property<int>("DieticiansId")
                        .HasColumnType("int");

                    b.Property<int>("VisitsId")
                        .HasColumnType("int");

                    b.HasKey("DieticiansId", "VisitsId");

                    b.HasIndex("VisitsId");

                    b.ToTable("DieticianVisit");
                });

            modelBuilder.Entity("DietPatient", b =>
                {
                    b.Property<int>("DietsId")
                        .HasColumnType("int");

                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.HasKey("DietsId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("DietPatient");
                });

            modelBuilder.Entity("MessagePatient", b =>
                {
                    b.Property<int>("MessagesId")
                        .HasColumnType("int");

                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.HasKey("MessagesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("MessagePatient");
                });

            modelBuilder.Entity("ModelsDB.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfficeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("ModelsDB.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DieteticianId")
                        .HasColumnType("int");

                    b.Property<int?>("DieticianId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DieticianId");

                    b.HasIndex("PatientId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("ModelsDB.Diet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DieteticianId")
                        .HasColumnType("int");

                    b.Property<int?>("DieticianId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DieticianId");

                    b.ToTable("Diet");
                });

            modelBuilder.Entity("ModelsDB.Diploma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DieteticianId")
                        .HasColumnType("int");

                    b.Property<int?>("DieticianId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoDiplomaLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoDiplomaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DieticianId");

                    b.ToTable("Diploma");
                });

            modelBuilder.Entity("ModelsDB.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<string>("DishPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodCatalogId")
                        .HasColumnType("int");

                    b.Property<float>("Glycemic")
                        .HasColumnType("real");

                    b.Property<int>("IngridientId")
                        .HasColumnType("int");

                    b.Property<float>("Macronutrient")
                        .HasColumnType("real");

                    b.Property<int>("MeasureId")
                        .HasColumnType("int");

                    b.Property<float>("Micronutrient")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodCatalogId");

                    b.HasIndex("IngridientId");

                    b.HasIndex("MeasureId");

                    b.HasIndex("RecipesId");

                    b.ToTable("Dish");
                });

            modelBuilder.Entity("ModelsDB.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("ModelsDB.FoodCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CatalogName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DieteticianId")
                        .HasColumnType("int");

                    b.Property<int?>("DieticianId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DieticianId");

                    b.ToTable("FoodCatalog");
                });

            modelBuilder.Entity("ModelsDB.Functionality.CategoryOfDiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryOfDiet");
                });

            modelBuilder.Entity("ModelsDB.Functionality.DayWeek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DayWeek");
                });

            modelBuilder.Entity("ModelsDB.Functionality.MealTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("DishTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealTime");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Sex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sex");
                });

            modelBuilder.Entity("ModelsDB.Functionality.SingleDiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryOfDietId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayWeekId")
                        .HasColumnType("int");

                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<int>("MealTimeHour")
                        .HasColumnType("int");

                    b.Property<int>("MealTimeId")
                        .HasColumnType("int");

                    b.Property<int>("MealTimeMinute")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryOfDietId");

                    b.HasIndex("DayWeekId");

                    b.HasIndex("DietId");

                    b.HasIndex("MealTimeId");

                    b.ToTable("SingleDiet");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Term");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Visit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateVisit")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TermId");

                    b.ToTable("Visit");
                });

            modelBuilder.Entity("ModelsDB.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Calories")
                        .HasColumnType("real");

                    b.Property<float>("Glycemic")
                        .HasColumnType("real");

                    b.Property<float>("Macronutrient")
                        .HasColumnType("real");

                    b.Property<float>("Micronutrient")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("ModelsDB.Layout.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LayoutCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LayoutCategoryId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("ModelsDB.Layout.Carousel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LayoutCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LayoutCategoryId");

                    b.ToTable("Carousel");
                });

            modelBuilder.Entity("ModelsDB.Layout.Footer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Footer");
                });

            modelBuilder.Entity("ModelsDB.Layout.LayoutCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LayoutCategory");
                });

            modelBuilder.Entity("ModelsDB.Layout.LayoutPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("CarouselId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewsId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CarouselId");

                    b.HasIndex("NewsId");

                    b.ToTable("LayoutPhoto");
                });

            modelBuilder.Entity("ModelsDB.Layout.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FooterId")
                        .HasColumnType("int");

                    b.Property<int>("LayoutCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.HasIndex("LayoutCategoryId");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("ModelsDB.Layout.Navbar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LayoutCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LayoutCategoryId");

                    b.ToTable("Navbar");
                });

            modelBuilder.Entity("ModelsDB.Layout.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("ModelsDB.Layout.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FooterId")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FooterId");

                    b.HasIndex("LinkId");

                    b.ToTable("SocialMedia");
                });

            modelBuilder.Entity("ModelsDB.Layout.SubTab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("LinkId")
                        .HasColumnType("int");

                    b.Property<int?>("TabId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("TabId");

                    b.ToTable("SubTab");
                });

            modelBuilder.Entity("ModelsDB.Layout.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("NavbarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NavbarId");

                    b.ToTable("Tab");
                });

            modelBuilder.Entity("ModelsDB.Layout.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.CategoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryType");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.Content", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PhotoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("FileCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("FileCategoryId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.FileCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryTypeId");

                    b.ToTable("FileCategory");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.Manual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<int>("FileCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ContentId");

                    b.HasIndex("FileCategoryId");

                    b.ToTable("Manual");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.Tooltip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tooltip");
                });

            modelBuilder.Entity("ModelsDB.Measure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Measure");
                });

            modelBuilder.Entity("ModelsDB.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("ModelsDB.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isVisibleToPatient")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("UserId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ModelsDB.Office", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Office");
                });

            modelBuilder.Entity("ModelsDB.PatientCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("SexId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("RatingId");

                    b.HasIndex("SexId");

                    b.ToTable("PatientCard");
                });

            modelBuilder.Entity("ModelsDB.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("ModelsDB.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Step")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("ModelsDB.SingleTestEqual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("TestEqualId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<float>("test1")
                        .HasColumnType("real");

                    b.Property<float>("test2")
                        .HasColumnType("real");

                    b.Property<float>("test3")
                        .HasColumnType("real");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TestEqualId");

                    b.ToTable("SingleTestEqual");
                });

            modelBuilder.Entity("ModelsDB.Survey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Heigth")
                        .HasColumnType("real");

                    b.Property<DateTime>("MeasureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientCardId")
                        .HasColumnType("int");

                    b.Property<float>("Weith")
                        .HasColumnType("real");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientCardId");

                    b.ToTable("Survey");
                });

            modelBuilder.Entity("ModelsDB.TestEqual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("PatientCardId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientCardId");

                    b.HasIndex("PatientId");

                    b.ToTable("TestEqual");
                });

            modelBuilder.Entity("ModelsDB.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("isDietician")
                        .HasColumnType("bit");

                    b.Property<bool>("isPatient")
                        .HasColumnType("bit");

                    b.Property<string>("whoAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoDeleted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("whoUpdated")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("PatientRating", b =>
                {
                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.Property<int>("RatingsId")
                        .HasColumnType("int");

                    b.HasKey("PatientsId", "RatingsId");

                    b.HasIndex("RatingsId");

                    b.ToTable("PatientRating");
                });

            modelBuilder.Entity("PatientVisit", b =>
                {
                    b.Property<int>("PatientsId")
                        .HasColumnType("int");

                    b.Property<int>("VisitsId")
                        .HasColumnType("int");

                    b.HasKey("PatientsId", "VisitsId");

                    b.HasIndex("VisitsId");

                    b.ToTable("PatientVisit");
                });

            modelBuilder.Entity("ModelsDB.Dietician", b =>
                {
                    b.HasBaseType("ModelsDB.User");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.HasIndex("RatingId");

                    b.ToTable("Dietician");
                });

            modelBuilder.Entity("ModelsDB.Patient", b =>
                {
                    b.HasBaseType("ModelsDB.User");

                    b.Property<int>("DieticianId")
                        .HasColumnType("int");

                    b.Property<int?>("SexId")
                        .HasColumnType("int");

                    b.HasIndex("DieticianId");

                    b.HasIndex("SexId");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("DieticianMessage", b =>
                {
                    b.HasOne("ModelsDB.Dietician", null)
                        .WithMany()
                        .HasForeignKey("DieticiansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Message", null)
                        .WithMany()
                        .HasForeignKey("MessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DieticianOffice", b =>
                {
                    b.HasOne("ModelsDB.Dietician", null)
                        .WithMany()
                        .HasForeignKey("DieticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Office", null)
                        .WithMany()
                        .HasForeignKey("OfficesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DieticianVisit", b =>
                {
                    b.HasOne("ModelsDB.Dietician", null)
                        .WithMany()
                        .HasForeignKey("DieticiansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DietPatient", b =>
                {
                    b.HasOne("ModelsDB.Diet", null)
                        .WithMany()
                        .HasForeignKey("DietsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MessagePatient", b =>
                {
                    b.HasOne("ModelsDB.Message", null)
                        .WithMany()
                        .HasForeignKey("MessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelsDB.Address", b =>
                {
                    b.HasOne("ModelsDB.Office", "Office")
                        .WithMany("Addresses")
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");
                });

            modelBuilder.Entity("ModelsDB.Comment", b =>
                {
                    b.HasOne("ModelsDB.Dietician", "Dietician")
                        .WithMany()
                        .HasForeignKey("DieticianId");

                    b.HasOne("ModelsDB.Patient", "Patient")
                        .WithMany("Comments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dietician");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ModelsDB.Diet", b =>
                {
                    b.HasOne("ModelsDB.Dietician", "Dietician")
                        .WithMany()
                        .HasForeignKey("DieticianId");

                    b.Navigation("Dietician");
                });

            modelBuilder.Entity("ModelsDB.Diploma", b =>
                {
                    b.HasOne("ModelsDB.Dietician", "Dietician")
                        .WithMany("Diplomas")
                        .HasForeignKey("DieticianId");

                    b.Navigation("Dietician");
                });

            modelBuilder.Entity("ModelsDB.Dish", b =>
                {
                    b.HasOne("ModelsDB.FoodCatalog", "FoodCatalog")
                        .WithMany("Dishes")
                        .HasForeignKey("FoodCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Ingredient", "Ingridient")
                        .WithMany("Dish")
                        .HasForeignKey("IngridientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Measure", "Measure")
                        .WithMany("Dishes")
                        .HasForeignKey("MeasureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Recipe", "Recipes")
                        .WithMany("Dishes")
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodCatalog");

                    b.Navigation("Ingridient");

                    b.Navigation("Measure");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("ModelsDB.FoodCatalog", b =>
                {
                    b.HasOne("ModelsDB.Dietician", "Dietician")
                        .WithMany("FoodCatalogs")
                        .HasForeignKey("DieticianId");

                    b.Navigation("Dietician");
                });

            modelBuilder.Entity("ModelsDB.Functionality.SingleDiet", b =>
                {
                    b.HasOne("ModelsDB.Functionality.CategoryOfDiet", "CategoryOfDiet")
                        .WithMany("SingleDiets")
                        .HasForeignKey("CategoryOfDietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.DayWeek", "DayWeek")
                        .WithMany("SingleDiets")
                        .HasForeignKey("DayWeekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Diet", "Diet")
                        .WithMany("SingleDiets")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.MealTime", "MealTime")
                        .WithMany("SingleDiets")
                        .HasForeignKey("MealTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryOfDiet");

                    b.Navigation("DayWeek");

                    b.Navigation("Diet");

                    b.Navigation("MealTime");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Visit", b =>
                {
                    b.HasOne("ModelsDB.Functionality.Status", "Status")
                        .WithMany("Visits")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.Term", "Term")
                        .WithMany("Visits")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("ModelsDB.Layout.Article", b =>
                {
                    b.HasOne("ModelsDB.Layout.LayoutCategory", "LayoutCategory")
                        .WithMany()
                        .HasForeignKey("LayoutCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCategory");
                });

            modelBuilder.Entity("ModelsDB.Layout.Carousel", b =>
                {
                    b.HasOne("ModelsDB.Layout.LayoutCategory", "LayoutCategory")
                        .WithMany()
                        .HasForeignKey("LayoutCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCategory");
                });

            modelBuilder.Entity("ModelsDB.Layout.Footer", b =>
                {
                    b.HasOne("ModelsDB.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("ModelsDB.Layout.LayoutPhoto", b =>
                {
                    b.HasOne("ModelsDB.Layout.Article", null)
                        .WithMany("Photos")
                        .HasForeignKey("ArticleId");

                    b.HasOne("ModelsDB.Layout.Carousel", null)
                        .WithMany("Photos")
                        .HasForeignKey("CarouselId");

                    b.HasOne("ModelsDB.Layout.News", null)
                        .WithMany("Photos")
                        .HasForeignKey("NewsId");
                });

            modelBuilder.Entity("ModelsDB.Layout.Link", b =>
                {
                    b.HasOne("ModelsDB.Layout.Footer", null)
                        .WithMany("Links")
                        .HasForeignKey("FooterId");

                    b.HasOne("ModelsDB.Layout.LayoutCategory", "LayoutCategory")
                        .WithMany()
                        .HasForeignKey("LayoutCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCategory");
                });

            modelBuilder.Entity("ModelsDB.Layout.Navbar", b =>
                {
                    b.HasOne("ModelsDB.Layout.LayoutCategory", "LayoutCategory")
                        .WithMany()
                        .HasForeignKey("LayoutCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LayoutCategory");
                });

            modelBuilder.Entity("ModelsDB.Layout.SocialMedia", b =>
                {
                    b.HasOne("ModelsDB.Layout.Footer", null)
                        .WithMany("SocialMedia")
                        .HasForeignKey("FooterId");

                    b.HasOne("ModelsDB.Layout.Link", "Link")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ModelsDB.Layout.SubTab", b =>
                {
                    b.HasOne("ModelsDB.Layout.Link", "Link")
                        .WithMany()
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Layout.Tab", null)
                        .WithMany("SubTabs")
                        .HasForeignKey("TabId");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("ModelsDB.Layout.Tab", b =>
                {
                    b.HasOne("ModelsDB.Layout.Navbar", null)
                        .WithMany("Tabs")
                        .HasForeignKey("NavbarId");
                });

            modelBuilder.Entity("ModelsDB.Layout.Tag", b =>
                {
                    b.HasOne("ModelsDB.Layout.Article", null)
                        .WithMany("Tags")
                        .HasForeignKey("ArticleId");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.Document", b =>
                {
                    b.HasOne("ModelsDB.ManualPanel.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.ManualPanel.FileCategory", "FileCategory")
                        .WithMany()
                        .HasForeignKey("FileCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("FileCategory");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.FileCategory", b =>
                {
                    b.HasOne("ModelsDB.ManualPanel.CategoryType", "CategoryType")
                        .WithMany()
                        .HasForeignKey("CategoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryType");
                });

            modelBuilder.Entity("ModelsDB.ManualPanel.Manual", b =>
                {
                    b.HasOne("ModelsDB.ManualPanel.Content", "Content")
                        .WithMany()
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.ManualPanel.FileCategory", "FileCategory")
                        .WithMany()
                        .HasForeignKey("FileCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");

                    b.Navigation("FileCategory");
                });

            modelBuilder.Entity("ModelsDB.Note", b =>
                {
                    b.HasOne("ModelsDB.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ModelsDB.PatientCard", b =>
                {
                    b.HasOne("ModelsDB.Patient", "Patient")
                        .WithMany("PatientCard")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Rating", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.Sex", "Sex")
                        .WithMany()
                        .HasForeignKey("SexId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Rating");

                    b.Navigation("Sex");
                });

            modelBuilder.Entity("ModelsDB.SingleTestEqual", b =>
                {
                    b.HasOne("ModelsDB.TestEqual", "TestEqual")
                        .WithMany("SingleTestEqual")
                        .HasForeignKey("TestEqualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestEqual");
                });

            modelBuilder.Entity("ModelsDB.Survey", b =>
                {
                    b.HasOne("ModelsDB.PatientCard", "PatientCard")
                        .WithMany("Surveys")
                        .HasForeignKey("PatientCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PatientCard");
                });

            modelBuilder.Entity("ModelsDB.TestEqual", b =>
                {
                    b.HasOne("ModelsDB.PatientCard", null)
                        .WithMany("testEqual")
                        .HasForeignKey("PatientCardId");

                    b.HasOne("ModelsDB.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ModelsDB.User", b =>
                {
                    b.HasOne("ModelsDB.Address", "Address")
                        .WithMany("Users")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("PatientRating", b =>
                {
                    b.HasOne("ModelsDB.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Rating", null)
                        .WithMany()
                        .HasForeignKey("RatingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatientVisit", b =>
                {
                    b.HasOne("ModelsDB.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.Visit", null)
                        .WithMany()
                        .HasForeignKey("VisitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModelsDB.Dietician", b =>
                {
                    b.HasOne("ModelsDB.User", null)
                        .WithOne()
                        .HasForeignKey("ModelsDB.Dietician", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Rating", "Rating")
                        .WithMany("Dieticians")
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("ModelsDB.Patient", b =>
                {
                    b.HasOne("ModelsDB.Dietician", "Dietician")
                        .WithMany("Patients")
                        .HasForeignKey("DieticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.User", null)
                        .WithOne()
                        .HasForeignKey("ModelsDB.Patient", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("ModelsDB.Functionality.Sex", null)
                        .WithMany("Patients")
                        .HasForeignKey("SexId");

                    b.Navigation("Dietician");
                });

            modelBuilder.Entity("ModelsDB.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ModelsDB.Diet", b =>
                {
                    b.Navigation("SingleDiets");
                });

            modelBuilder.Entity("ModelsDB.FoodCatalog", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("ModelsDB.Functionality.CategoryOfDiet", b =>
                {
                    b.Navigation("SingleDiets");
                });

            modelBuilder.Entity("ModelsDB.Functionality.DayWeek", b =>
                {
                    b.Navigation("SingleDiets");
                });

            modelBuilder.Entity("ModelsDB.Functionality.MealTime", b =>
                {
                    b.Navigation("SingleDiets");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Sex", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Status", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ModelsDB.Functionality.Term", b =>
                {
                    b.Navigation("Visits");
                });

            modelBuilder.Entity("ModelsDB.Ingredient", b =>
                {
                    b.Navigation("Dish");
                });

            modelBuilder.Entity("ModelsDB.Layout.Article", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("ModelsDB.Layout.Carousel", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ModelsDB.Layout.Footer", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("SocialMedia");
                });

            modelBuilder.Entity("ModelsDB.Layout.Navbar", b =>
                {
                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("ModelsDB.Layout.News", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("ModelsDB.Layout.Tab", b =>
                {
                    b.Navigation("SubTabs");
                });

            modelBuilder.Entity("ModelsDB.Measure", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("ModelsDB.Office", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("ModelsDB.PatientCard", b =>
                {
                    b.Navigation("Surveys");

                    b.Navigation("testEqual");
                });

            modelBuilder.Entity("ModelsDB.Rating", b =>
                {
                    b.Navigation("Dieticians");
                });

            modelBuilder.Entity("ModelsDB.Recipe", b =>
                {
                    b.Navigation("Dishes");
                });

            modelBuilder.Entity("ModelsDB.TestEqual", b =>
                {
                    b.Navigation("SingleTestEqual");
                });

            modelBuilder.Entity("ModelsDB.User", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ModelsDB.Dietician", b =>
                {
                    b.Navigation("Diplomas");

                    b.Navigation("FoodCatalogs");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("ModelsDB.Patient", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PatientCard");
                });
#pragma warning restore 612, 618
        }
    }
}
